<a href="https://colab.research.google.com/github/Ashiqali78/Deep_Learning/blob/main/Autograd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

It is used for calculating complex derivatives in NN

In [3]:
import torch

In [1]:
#1 Calculate the derivative of the following
"y=x**2"

'y=x**2'

In [5]:
x = torch.tensor(3.0, requires_grad=True)

In [6]:
y = x**2

In [12]:
print(x)
print(y)

tensor(3., requires_grad=True)
tensor(9., grad_fn=<PowBackward0>)


In [9]:
# y.backward()

In [13]:
x.grad

tensor(6.)

In [15]:
#2
a = torch.tensor(3.0, requires_grad=True)

In [16]:
b = a**2

In [17]:
c = torch.sin(b)

In [18]:
print(a)
print(b)
print(c)

tensor(3., requires_grad=True)
tensor(9., grad_fn=<PowBackward0>)
tensor(0.4121, grad_fn=<SinBackward0>)


In [19]:
c.backward()

In [21]:
a.grad

tensor(-5.4668)

In [23]:
x = torch.tensor(6.5)
y = torch.tensor(0.0)

In [25]:
w = torch.tensor(1.0, requires_grad=True)
b = torch.tensor(0.0, requires_grad=True)

In [26]:
z = w*x + b
z

tensor(6.5000, grad_fn=<AddBackward0>)

In [27]:
y_pred = torch.sigmoid(z)
y_pred

tensor(0.9985, grad_fn=<SigmoidBackward0>)

In [31]:
import torch.nn.functional as F
loss = F.binary_cross_entropy(y_pred, y)
loss

tensor(6.5015, grad_fn=<BinaryCrossEntropyBackward0>)

In [32]:
loss.backward()

In [33]:
print(w.grad)
print(b.grad)

tensor(6.4902)
tensor(0.9985)


In [34]:
# on vectors
x = torch.tensor([1,0, 4.0, -10.0], requires_grad=True)

In [37]:
y = (x**2).mean()

In [38]:
y.backward()

In [39]:
x.grad

tensor([ 0.5000,  0.0000,  2.0000, -5.0000])

In [40]:
# Clearing Grads
x.grad.zero_()

tensor([0., 0., 0., 0.])

In [41]:
x.requires_grad_(False)
# disable the tracking of x

tensor([  1.,   0.,   4., -10.])