<a href="https://colab.research.google.com/github/Ashiqali78/Deep_Learning/blob/main/PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [2]:
print(torch.__version__)

2.5.1+cu124


In [3]:
#for checking GPU avalibality
if torch.cuda.is_available():
  print("GPU is avalible")
  print(torch.cuda.get_device_name(0))
else:
  print("GPU is not avalible")

GPU is avalible
Tesla T4


In [4]:
x=np.ones(5)
x

array([1., 1., 1., 1., 1.])

In [5]:
y=torch.from_numpy(x)
y

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [6]:
np.add(x,1,out=x)

array([2., 2., 2., 2., 2.])

In [7]:
print(x)
print(y)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [27]:
# 3 ways to create a tensor from pytorch
arr = [[6,11],[0,1],[5,11]]
pyTensor = torch.Tensor(arr)
print(pyTensor)
print(type(pyTensor))

tensor([[ 6., 11.],
        [ 0.,  1.],
        [ 5., 11.]])
<class 'torch.Tensor'>


In [9]:
arr2 = torch.Tensor([[1,10],[2,20],[3,30]])
print(arr2)
print(type(arr2))

tensor([[ 1., 10.],
        [ 2., 20.],
        [ 3., 30.]])
<class 'torch.Tensor'>


In [28]:
arr1 = torch.Tensor([[4,10],[5,50],[6,3]])
print(arr1)
print(type(arr1))

tensor([[ 4., 10.],
        [ 5., 50.],
        [ 6.,  3.]])
<class 'torch.Tensor'>


In [10]:
tensor1 = torch.ones((2,2))
tensor2 = torch.rand((2,2))
result = tensor1+tensor2
print(result)

tensor([[1.7287, 1.9453],
        [1.5595, 1.3933]])


In [11]:
print(torch.arange(0,10,2))

tensor([0, 2, 4, 6, 8])


In [12]:
iden = torch.eye(4)
print(iden)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])


**Tensor Shape**

In [13]:
print(iden.shape)

torch.Size([4, 4])


In [14]:
# copy tensor shape
iden1 = torch.empty_like(iden)
iden1

tensor([[7.8804e-35, 0.0000e+00, 6.3733e+34, 4.3411e-41],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [16]:
iden1.dtype

torch.float32

In [18]:
intTen = torch.tensor([1.0, 2.0, 3.0, 4.0, 5.0], dtype = torch.int32)
print(intTen)
intTen.dtype

tensor([1, 2, 3, 4, 5], dtype=torch.int32)


torch.int32

In [29]:
print(arr1)
print(arr2)

tensor([[ 4., 10.],
        [ 5., 50.],
        [ 6.,  3.]])
tensor([[ 1., 10.],
        [ 2., 20.],
        [ 3., 30.]])


In [30]:
# Math Operations on these tensors
print(arr1*arr2)

tensor([[   4.,  100.],
        [  10., 1000.],
        [  18.,   90.]])


In [31]:
# .add_ is used for memory efficiency perform inplace operations
tensor1 = torch.rand(2,3)
tensor2 = torch.rand(2,3)
print(tensor1)
print(tensor2)

tensor([[0.7992, 0.0334, 0.9613],
        [0.2801, 0.2067, 0.4554]])
tensor([[0.3266, 0.9248, 0.9740],
        [0.1044, 0.8869, 0.7817]])


In [32]:
tensor1.add_(tensor2)
# all the changes are store back to the tensor1 for memory saving.

tensor([[1.1258, 0.9582, 1.9353],
        [0.3845, 1.0936, 1.2371]])

In [33]:
print(tensor1)

tensor([[1.1258, 0.9582, 1.9353],
        [0.3845, 1.0936, 1.2371]])


In [34]:
torch.relu(tensor1)

tensor([[1.1258, 0.9582, 1.9353],
        [0.3845, 1.0936, 1.2371]])

In [ ]:
# .clone() is used ofr copy the tensor

##Tensor operations on GPU

In [35]:
torch.cuda.is_available()

True

In [36]:
device = torch.device('cuda')

In [37]:
gputensor = torch.rand((2,3),device=device)
print(gputensor)

tensor([[0.9169, 0.7246, 0.9967],
        [0.1080, 0.7334, 0.6722]], device='cuda:0')


In [38]:
# move cpu tensor to gpu
tensor1.to(device)

tensor([[1.1258, 0.9582, 1.9353],
        [0.3845, 1.0936, 1.2371]], device='cuda:0')

###CPU vs GPU

In [40]:
import time

size = 10000
# CPU
mat_cpu1 = torch.rand(size,size)
mat_cpu2 = torch.rand(size,size)

start_time = time.time()
result_cpu = torch.matmul(mat_cpu1, mat_cpu2)
cpu_time = time.time() - start_time
print("CPU time: ", cpu_time)

# GPU
mat_gpu1 = mat_cpu1.to(device)
mat_gpu2 = mat_cpu2.to(device)

start_time = time.time()
result_gpu = torch.matmul(mat_gpu1, mat_gpu2)
gpu_time = time.time() - start_time
print("GPU time: ", gpu_time)

print("(CPU time / GPU time)", cpu_time / gpu_time)

CPU time:  16.075580596923828
GPU time:  0.0006313323974609375
(CPU time / GPU time) 25462.94259818731


**Reshaping the tensor**
reshape, flatten, sqeeze, unsqueeze, permute etc

In [41]:
a = torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [43]:
print(a.reshape(2,2,2,2))
print(a.flatten())


tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
